services:
  app:
    build: .
    container_name: mysqlscrewdriver-public
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION    
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    working_dir: /app
    command: streamlit run main.py
    stdin_open: true
    tty: true